export const cards = [
    {
        rank: 'A',
        suitCenter: './static/peaks-center.png',
        suitCorner: './static/peaks-corner.png',
        isOpened: true,
    },
    {
        rank: 'K',
        suitCenter: './static/peaks-center.png',
        suitCorner: './static/peaks-corner.png',
        isOpened: true,
    },
    {
        rank: 'Q',
        suitCenter: './static/peaks-center.png',
        suitCorner: './static/peaks-corner.png',
        isOpened: true,
    },
    {
        rank: 'J',
        suitCenter: './static/peaks-center.png',
        suitCorner: './static/peaks-corner.png',
        isOpened: true,
    },
    {
        rank: '10',
        suitCenter: './static/peaks-center.png',
        suitCorner: './static/peaks-corner.png',
        isOpened: true,
    },
    {
        rank: '9',
        suitCenter: './static/peaks-center.png',
        suitCorner: './static/peaks-corner.png',
        isOpened: true,
    },
    {
        rank: '8',
        suitCenter: './static/peaks-center.png',
        suitCorner: './static/peaks-corner.png',
        isOpened: true,
    },
    {
        rank: '7',
        suitCenter: './static/peaks-center.png',
        suitCorner: './static/peaks-corner.png',
        isOpened: true,
    },
    {
        rank: '6',
        suitCenter: './static/peaks-center.png',
        suitCorner: './static/peaks-corner.png',
        isOpened: true,
    },
    {
        rank: 'A',
        suitCenter: './static/hearts-center.png',
        suitCorner: './static/hearts-corner.png',
        isOpened: true,
    },
    {
        rank: 'K',
        suitCenter: './static/hearts-center.png',
        suitCorner: './static/hearts-corner.png',
        isOpened: true,
    },
    {
        rank: 'Q',
        suitCenter: './static/hearts-center.png',
        suitCorner: './static/hearts-corner.png',
        isOpened: true,
    },
    {
        rank: 'J',
        suitCenter: './static/hearts-center.png',
        suitCorner: './static/hearts-corner.png',
        isOpened: true,
    },
    {
        rank: '10',
        suitCenter: './static/hearts-center.png',
        suitCorner: './static/hearts-corner.png',
        isOpened: true,
    },
    {
        rank: '9',
        suitCenter: './static/hearts-center.png',
        suitCorner: './static/hearts-corner.png',
        isOpened: true,
    },
    {
        rank: '8',
        suitCenter: './static/hearts-center.png',
        suitCorner: './static/hearts-corner.png',
        isOpened: true,
    },
    {
        rank: '7',
        suitCenter: './static/hearts-center.png',
        suitCorner: './static/hearts-corner.png',
        isOpened: true,
    },
    {
        rank: '6',
        suitCenter: './static/hearts-center.png',
        suitCorner: './static/hearts-corner.png',
        isOpened: true,
    },
    {
        rank: 'A',
        suitCenter: './static/diamonds-center.png',
        suitCorner: './static/diamonds-corner.png',
        isOpened: true,
    },
    {
        rank: 'K',
        suitCenter: './static/diamonds-center.png',
        suitCorner: './static/diamonds-corner.png',
        isOpened: true,
    },
    {
        rank: 'Q',
        suitCenter: './static/diamonds-center.png',
        suitCorner: './static/diamonds-corner.png',
        isOpened: true,
    },
    {
        rank: 'J',
        suitCenter: './static/diamonds-center.png',
        suitCorner: './static/diamonds-corner.png',
        isOpened: true,
    },
    {
        rank: '10',
        suitCenter: './static/diamonds-center.png',
        suitCorner: './static/diamonds-corner.png',
        isOpened: true,
    },
    {
        rank: '9',
        suitCenter: './static/diamonds-center.png',
        suitCorner: './static/diamonds-corner.png',
        isOpened: true,
    },
    {
        rank: '8',
        suitCenter: './static/diamonds-center.png',
        suitCorner: './static/diamonds-corner.png',
        isOpened: true,
    },
    {
        rank: '7',
        suitCenter: './static/diamonds-center.png',
        suitCorner: './static/diamonds-corner.png',
        isOpened: true,
    },
    {
        rank: '6',
        suitCenter: './static/diamonds-center.png',
        suitCorner: './static/diamonds-corner.png',
        isOpened: true,
    },
    {
        rank: 'A',
        suitCenter: './static/clubs-center.png',
        suitCorner: './static/clubs-corner.png',
        isOpened: true,
    },
    {
        rank: 'K',
        suitCenter: './static/clubs-center.png',
        suitCorner: './static/clubs-corner.png',
        isOpened: true,
    },
    {
        rank: 'Q',
        suitCenter: './static/clubs-center.png',
        suitCorner: './static/clubs-corner.png',
        isOpened: true,
    },
    {
        rank: 'J',
        suitCenter: './static/clubs-center.png',
        suitCorner: './static/clubs-corner.png',
        isOpened: true,
    },
    {
        rank: '10',
        suitCenter: './static/clubs-center.png',
        suitCorner: './static/clubs-corner.png',
        isOpened: true,
    },
    {
        rank: '9',
        suitCenter: './static/clubs-center.png',
        suitCorner: './static/clubs-corner.png',
        isOpened: true,
    },
    {
        rank: '8',
        suitCenter: './static/clubs-center.png',
        suitCorner: './static/clubs-corner.png',
        isOpened: true,
    },
    {
        rank: '7',
        suitCenter: './static/clubs-center.png',
        suitCorner: './static/clubs-corner.png',
        isOpened: true,
    },
    {
        rank: '6',
        suitCenter: './static/clubs-center.png',
        suitCorner: './static/clubs-corner.png',
        isOpened: true,
    },
];
